// Copyright (c) 2026 BowenLabs. Astroid is MIT licensed.
//
// Workflow → Drizzle schema + the advance route.
//
// The schema half is a pure function of the config (regenerate freely); the
// route is SCAFFOLD-ONCE, because per-stage side effects — issue the invoice
// when packaging is signed, email the customer on every move — are the whole
// reason a project reaches for this module, and regenerating would erase them.

import {
  type WorkflowConfig,
  workflowAuditTable,
  workflowOverrideTable,
  workflowStages,
} from "./config.js";

/**
 * The Drizzle table sources a workflow adds: the audit table, and the override
 * log when enabled.
 *
 * The `stage` column itself is NOT emitted here — it belongs to the project's
 * own entity table (orders, applications, tickets), which Astroid doesn't own.
 * The returned `stageColumn` is the line to paste into it, which keeps the
 * ownership boundary honest rather than generating a table the project already has.
 */
export function generateWorkflowSchema(config: WorkflowConfig): {
  source: string;
  stageColumn: string;
} {
  const stages = workflowStages(config);
  const audit = workflowAuditTable(config);
  const override = workflowOverrideTable(config);
  // `orders` → `order_id`. Naive de-pluralisation on purpose: it covers the
  // real cases and a project that needs otherwise passes `auditIdColumn`.
  const fk = `${config.key.replace(/s$/, "")}_id`;
  const camel = (s: string) => s.replace(/_(\w)/g, (_, c) => c.toUpperCase());

  const lines: string[] = [
    "// Workflow tables — generated by Astroid from defineWorkflow().",
    "//",
    `// Stage model: \`${config.key}.stage\` is the stage currently IN PROGRESS`,
    `// (0–${stages.length - 1}); ${stages.length} means complete. A stage is done once its`,
    `// \`${audit}\` row exists.`,
    "//",
    `// Add this column to your \`${config.key}\` table:`,
    `//   stage: integer("stage").notNull().default(0),`,
    'import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";',
    "",
    `/** One row per COMPLETED stage — who signed it off, when, and what they recorded. */`,
    `export const ${camel(audit)} = sqliteTable(`,
    `  ${JSON.stringify(audit)},`,
    "  {",
    '    id: integer("id").primaryKey({ autoIncrement: true }),',
    `    ${camel(fk)}: text(${JSON.stringify(fk)}).notNull(),`,
    '    /** The stage this row completes (0-based). */',
    '    stage: integer("stage").notNull(),',
    "    /** Recorded values for the stage, [{ k, v }] JSON. */",
    '    specs: text("specs", { mode: "json" }).$type<{ k: string; v: string }[]>(),',
    '    initials: text("initials").notNull(),',
    '    /** Account id when the pipeline runs behind a portal. */',
    '    actorId: text("actor_id"),',
    '    signedAt: integer("signed_at", { mode: "timestamp" })',
    "      .notNull()",
    "      .$defaultFn(() => new Date()),",
    "  },",
    "  (t) => [",
    `    index(${JSON.stringify(`${audit}_entity_idx`)}).on(t.${camel(fk)}),`,
    "    // One sign-off per stage per item. The guarded advance already prevents",
    "    // a double move, and this makes a duplicate audit row impossible even if",
    "    // a future caller writes one directly.",
    `    uniqueIndex(${JSON.stringify(`${audit}_entity_stage_key`)}).on(t.${camel(fk)}, t.stage),`,
    "  ],",
    ");",
  ];

  if (override) {
    lines.push(
      "",
      "/** Out-of-band moves — sending an item back a stage, or skipping one.",
      " *  A pipeline you can override without a trace is one nobody trusts. */",
      `export const ${camel(override)} = sqliteTable(`,
      `  ${JSON.stringify(override)},`,
      "  {",
      '    id: integer("id").primaryKey({ autoIncrement: true }),',
      `    ${camel(fk)}: text(${JSON.stringify(fk)}).notNull(),`,
      '    /** "back" | "skip". */',
      '    action: text("action").notNull(),',
      '    initials: text("initials").notNull(),',
      '    station: text("station"),',
      '    at: integer("at", { mode: "timestamp" })',
      "      .notNull()",
      "      .$defaultFn(() => new Date()),",
      "  },",
      `  (t) => [index(${JSON.stringify(`${override}_entity_idx`)}).on(t.${camel(fk)})],`,
      ");",
    );
  }

  lines.push(
    "",
    "/** Stage labels, index === stage number. */",
    `export const ${config.key.toUpperCase()}_STAGES = ${JSON.stringify(stages.map((s) => s.label))} as const;`,
    "",
  );

  return { source: lines.join("\n"), stageColumn: 'stage: integer("stage").notNull().default(0),' };
}

/**
 * `src/pages/api/<key>/advance.ts` — the guarded advance route.
 *
 * Thin by design: `advanceWorkflowStage` owns the concurrency guard and the
 * status contract, so what's left here is authentication and the per-stage side
 * effects, which are the project's own business.
 */
export function generateWorkflowRoute(config: WorkflowConfig): string {
  const stages = workflowStages(config);
  const audit = workflowAuditTable(config);
  const fk = `${config.key.replace(/s$/, "")}_id`;

  return [
    `// Advance one ${config.key} item by a stage.`,
    "//",
    "// Scaffolded once; yours to edit. `advanceWorkflowStage` owns the part that",
    "// is easy to get wrong — the optimistic-concurrency guard, so two operators",
    "// pressing sign-off at the same moment can't run an item forward twice — and",
    "// returns a status rather than throwing, because a conflict is an ordinary",
    "// outcome of two people working at once.",
    "//",
    "// What belongs to you is below the call: the per-stage side effects. The",
    "// reference this generalizes issues the balance invoice when packaging is",
    "// signed and emails the customer on every other move.",
    'import type { APIRoute } from "astro";',
    'import { advanceWorkflowStage } from "astroidjs";',
    'import { env } from "cloudflare:workers";',
    "",
    "export const prerender = false;",
    "",
    `const STAGE_COUNT = ${stages.length};`,
    "",
    "export const POST: APIRoute = async ({ request, locals }) => {",
    "  // TODO: gate this. A pipeline advance is a privileged action — check the",
    "  // portal session/role here before anything else.",
    "  void locals;",
    "",
    "  const body = (await request.json().catch(() => null)) as {",
    "    id?: string;",
    "    stage?: number;",
    "    initials?: string;",
    "    specs?: { k: string; v: string }[];",
    "  } | null;",
    "",
    "  if (!body?.id || typeof body.stage !== \"number\") {",
    '    return Response.json({ ok: false, error: "Bad request" }, { status: 400 });',
    "  }",
    "",
    "  const result = await advanceWorkflowStage({",
    "    db: env.DB,",
    `    table: ${JSON.stringify(config.key)},`,
    `    auditTable: ${JSON.stringify(audit)},`,
    `    auditIdColumn: ${JSON.stringify(fk)},`,
    "    id: body.id,",
    "    expectedStage: body.stage,",
    "    stageCount: STAGE_COUNT,",
    '    actor: { initials: body.initials ?? "" },',
    "    specs: body.specs,",
    "  });",
    "",
    "  if (!result.ok) return Response.json(result, { status: result.status });",
    "",
    "  // TODO: per-stage side effects go here — `result.stage` is the stage now in",
    "  // progress, and `result.complete` is true once the last one is signed.",
    "",
    "  return Response.json(result);",
    "};",
    "",
  ].join("\n");
}
