// Copyright (c) 2026 BowenLabs. Astroid is MIT licensed.
//
// generateAstroidWorker / generateAstroidMiddleware — emit the Cloudflare Worker
// entrypoint and the Astro middleware a Louise site would otherwise hand-write.
// The worker's editor routes are composed in the fixed order from the route plan
// (routes.ts), so the "versionsRoute/searchRoute before pagesRoute" collision is
// impossible by construction. Pure string generation, like generateAstroidSchema.
//
// Two seams are marked with TODO(astroid) and filled by later slices: the auth
// `resolveEditor`, and the section-catalog `validate` on the pages routes.

import type { AstroidConfig } from "../config.js";
import { astroidPortal } from "../portal/config.js";
import { astroidCron, astroidUsesQueues } from "../queues/messages.js";
import { capturesInquiries } from "../schema/framework.js";
import { type AstroidEditorRouteName, astroidEditorRoutePlan } from "./routes.js";

// Astroid's default editable site_settings surface — the columns the Settings
// panel may write, and which of them hold a media-library image URL.
const DEFAULT_SETTINGS_COLUMNS = [
  "siteName",
  "tagline",
  "logoUrl",
  "faviconUrl",
  "brandColor",
  "secondaryColor",
  "tertiaryColor",
  "contactEmail",
  "contactPhone",
  "contactAddress",
  "socialLinks",
  "navLinks",
  "metaDescription",
  "defaultOgImageUrl",
  "disableIndexing",
];
const DEFAULT_SETTINGS_IMAGE_KEYS = ["logoUrl", "faviconUrl", "defaultOgImageUrl"];

/**
 * Generate the Worker entrypoint (`worker.ts`) from an Astroid config: the editor
 * routes in collision-free order, an R2 media-asset route, and the `composeWorker`
 * default export over Astro's SSR handler. Inquiry routes + the contact form are
 * emitted only when a brand captures inquiries.
 */
export function generateAstroidWorker(config: AstroidConfig): string {
  const inquiries = capturesInquiries(config);
  const queues = astroidUsesQueues(config);
  const cron = astroidCron(config);
  const mediaBase = config.deploy?.mediaBase ?? "/media";
  const seedName = config.theme.name;
  const plan = astroidEditorRoutePlan(config);

  const editorImports = [
    "DEFAULT_PAGE_FIELDS",
    ...new Set(plan.map((route) => route.factory)),
  ].sort();
  const tables = [
    "media",
    "pages",
    "pagesVersions",
    "siteSettings",
    ...(inquiries ? ["inquiries"] : []),
  ].sort();

  const routeCall = (name: AstroidEditorRouteName): string => {
    switch (name) {
      case "versions":
        return "versionsRoute({ table: pages, versionsTable: pagesVersions, config: pagesCollection, resolveEditor })";
      case "search":
        return "searchRoute({ table: pages, config: pagesCollection, resolveEditor })";
      case "pages":
        return 'pagesRoute({ table: pages, resolveEditor, fields: [...DEFAULT_PAGE_FIELDS, "sections"] })';
      case "save":
        return 'saveRoute({ resolveEditor, collections: { pages: { table: pages, fields: ["title", "seoTitle", "seoDescription"] } } })';
      case "settings":
        return "settingsRoute({ table: siteSettings, resolveEditor, columns: SETTINGS_COLUMNS, imageKeys: SETTINGS_IMAGE_KEYS, mediaBase: MEDIA_BASE })";
      case "media":
        return "mediaRoute({ table: media, resolveEditor })";
      case "editors":
        // Better Auth owns the `user` table (a NAME, not a Drizzle table), so this
        // route takes the default `"user"`; a `tablePrefix` would rename it.
        return 'editorsRoute({ table: "user", resolveEditor })';
      case "form":
        // `onSubmit` fires AFTER the insert and off the response path, so the
        // notify + confirm pair is store-and-forward by construction: the
        // submission is already durable and mail can fail without the visitor
        // ever knowing. Unprovisioned mail logs instead of sending.
        // The `await` + block body is load-bearing: `onSubmit` returns
        // `void | Promise<void>`, and sendInquiryMail resolves to delivery
        // results nobody here reads.
        return "formRoute({ form: contactForm, rateLimitKv: (env) => env.RL, onSubmit: async (values, env) => { await sendInquiryMail(astroidConfig, env, values); } })";
      case "inquiries":
        return "inquiriesRoute({ table: inquiries, resolveEditor })";
      case "seed":
        return `seedRoute({ table: siteSettings, resolveEditor, defaults: { siteName: ${JSON.stringify(seedName)} } })`;
    }
  };

  const lines: string[] = [];
  const p = (s = "") => lines.push(s);

  p("// Generated by astroidjs — do not hand-edit.");
  p("// Source: your defineAstroid config. The editor route ORDER is fixed by");
  p("// Astroid to avoid matcher collisions — see each route's note below.");
  p('import { handle } from "@astrojs/cloudflare/handler";');
  p("import {");
  for (const name of editorImports) p(`  ${name},`);
  p('} from "louise-toolkit/editor";');
  if (inquiries) p('import { defineForm } from "louise-toolkit/forms";');
  if (queues) p('import { processBatch } from "louise-toolkit/queues";');
  p('import { composeWorker, type WorkerRoute } from "louise-toolkit/worker";');
  if (inquiries) p('import { inquiriesForm } from "louise-toolkit/db";');
  p(`import { ${tables.join(", ")} } from "./schema.js";`);
  const astroidImports = [
    "astroidPagesCollection",
    ...(inquiries ? ["sendInquiryMail"] : []),
    ...(queues ? ["type AstroidQueueMessage"] : []),
  ].sort();
  p(`import { ${astroidImports.join(", ")} } from "astroidjs";`);
  // The config lives at the PROJECT ROOT (create-astroid writes it there); this
  // file is src/worker.ts, so the specifier is `../`, not `./`.
  p('import astroidConfig from "../astroid.config.js";');
  p("// TODO(astroid): your AUTH seam. resolveEditor resolves the editor session");
  p("// from a request; a truthy result authorizes editor writes. A generated auth");
  p("// module is a later slice.");
  p('import { resolveEditor } from "./auth.js";');
  if (queues) {
    p("// Your QUEUE seam: what each message actually does. Scaffolded once and");
    p("// yours to edit — `astroidQueueHandler` there covers the catalog dispatch.");
    p('import { handleQueueMessage } from "./queue.js";');
  }
  p();
  p(`const MEDIA_BASE = ${JSON.stringify(mediaBase)};`);
  p("const pagesCollection = astroidPagesCollection(astroidConfig);");
  p();
  p("// Editable site_settings columns the Settings panel may write, and which of");
  p("// them resolve to a media-library asset.");
  p(`const SETTINGS_COLUMNS = ${JSON.stringify(DEFAULT_SETTINGS_COLUMNS)};`);
  p(`const SETTINGS_IMAGE_KEYS = ${JSON.stringify(DEFAULT_SETTINGS_IMAGE_KEYS)};`);
  if (inquiries) {
    p();
    p("// Public contact form: the built-in inquiries fields + silent spam");
    p("// heuristics (a honeypot + a minimum time-since-render).");
    p(
      'const contactForm = defineForm({ name: "inquiries", fields: inquiriesForm.fields, spam: { honeypot: "website", minSeconds: 2, rateLimit: { max: 5, windowSec: 60 } } });',
    );
  }
  p();
  p("// `sections` writes are validated against the section catalog before they");
  p("// persist — Astroid wires `assertValidSections` + `sanitizeSectionsRichText`");
  p("// into the pages collection's beforeChange hook (src/schema.ts's config), so");
  p("// every route below inherits it. An unknown `_type`, a field of the wrong");
  p("// shape, or a setting outside its declared options is a 422, not a hole in");
  p("// the page.");
  p("const editorRoutes: WorkerRoute<CloudflareEnv>[] = [");
  for (const route of plan) {
    p(`  // ${route.note}`);
    p(`  ${routeCall(route.name)},`);
  }
  p("];");
  p();
  p("// Stream uploaded media back from R2 at MEDIA_BASE (self-hosted, no public bucket).");
  p("const mediaAssetRoute: WorkerRoute<CloudflareEnv> = async (request, env) => {");
  p("  const url = new URL(request.url);");
  p("  if (!url.pathname.startsWith(`${MEDIA_BASE}/`)) return undefined;");
  p("  const key = decodeURIComponent(url.pathname.slice(MEDIA_BASE.length + 1));");
  p("  if (!key) return undefined;");
  p("  const obj = await env.MEDIA.get(key);");
  p('  if (!obj) return new Response("Not found", { status: 404 });');
  p("  const headers = new Headers();");
  p("  obj.writeHttpMetadata(headers);");
  p('  headers.set("etag", obj.httpEtag);');
  p('  headers.set("cache-control", "public, max-age=31536000, immutable");');
  p('  headers.set("x-content-type-options", "nosniff");');
  p("  return new Response(obj.body, { headers });");
  p("};");
  p();
  // The queue message type parameter is what gives the `queue` consumer below a
  // typed `MessageBatch` instead of `MessageBatch<unknown>`.
  p(
    queues
      ? "export default composeWorker<CloudflareEnv, AstroidQueueMessage>({"
      : "export default composeWorker<CloudflareEnv>({",
  );
  p("  routes: [...editorRoutes, mediaAssetRoute],");
  p("  fetch: (request, env, ctx) => handle(request, env, ctx),");
  if (queues) {
    p("  // Queue consumer. `processBatch` acks or retries each message");
    p("  // INDEPENDENTLY, so one poisoned message can't block the rest of the");
    p("  // batch from acking; Cloudflare routes it to the DLQ once it exceeds");
    p("  // max_retries (see wrangler.jsonc).");
    p(
      "  queue: (batch, env) => processBatch(batch, (message) => handleQueueMessage(env, message)),",
    );
    if (cron) {
      p("  // Cron safety net. Webhooks get missed — a provider outage, a deploy");
      p("  // mid-delivery, a DLQ'd message — and without this the site serves");
      p("  // stale data until a human notices. Enqueued rather than run inline so");
      p("  // it takes the same retry + DLQ path as everything else.");
      p("  scheduled: (_controller, env, ctx) => {");
      p('    ctx.waitUntil(env.COMMERCE_QUEUE.send({ kind: "catalog_refresh" }));');
      p("  },");
    }
  }
  p("});");
  p();

  return lines.join("\n");
}

/**
 * Generate the Astro middleware (`middleware.ts`) from an Astroid config: the
 * shared Louise flow (rate-limit the unauthenticated POST surface → resolve editor
 * session + sticky `?louise` edit mode → content-freshness + security headers) via
 * `createLouiseMiddleware`.
 *
 * The rate rules are NOT emitted as literals here — the file calls
 * `astroidRateRules(astroidConfig)`, so the set stays real data in the package
 * (testable, and a `match` predicate survives, which a serialized literal could
 * not). Enabling a portal or commerce in the config adds that surface's rules
 * with no regeneration of this file at all.
 *
 * CSP: `astro.config.mjs` enables `security.csp` (via `astroidSecurity`), so
 * Astro emits a hash-based `content-security-policy` response header on every SSR
 * page and owns `script-src`. The `cspStyleSrc` below tells
 * `createLouiseMiddleware` to rewrite that header's `style-src` to
 * `'self' 'unsafe-inline'` — a hash-based `style-src` would, per spec, void the
 * `'unsafe-inline'` that Louise's data-driven `style=""` carriers and the
 * editor's runtime-injected `<style>` require. Script hashes are left verbatim,
 * and the inlined `data:` brand font is auto-allowed.
 */
export function generateAstroidMiddleware(config: AstroidConfig): string {
  // Louise's brand font is bundled + base64-inlined (no Google Fonts host to
  // allow); createLouiseMiddleware auto-allows `data:` fonts in the CSP, so the
  // inlined @font-face needs no manual `font-src` entry.
  const cspStyleSrc = "'self' 'unsafe-inline'";
  const portal = astroidPortal(config);
  return [
    "// Generated by astroidjs — do not hand-edit.",
    "// The shared Louise middleware: rate-limit the unauthenticated POST surfaces,",
    "// then resolve the editor session + sticky ?louise edit mode, then apply",
    "// content-freshness + transport-security headers, and rewrite the style-src of",
    "// the CSP header Astro's security.csp emits so Louise's data-driven inline",
    "// styles + inlined data: brand font are allowed.",
    'import { env } from "cloudflare:workers";',
    'import { createLouiseMiddleware } from "louise-toolkit/astro";',
    portal
      ? 'import { astroidPortalGuardConfig, astroidRateRules, guardResponse, portalGuard, resolvePortalSession } from "astroidjs";'
      : 'import { astroidRateRules } from "astroidjs";',
    'import astroidConfig from "../astroid.config.js";',
    "// TODO(astroid): your AUTH seam — same resolveEditor as the generated worker.ts.",
    'import { resolveEditor } from "./auth.js";',
    // The portal's resolver lives in its OWN module, not the editor's auth
    // seam — they're separate Better Auth instances and must not share a file.
    ...(portal ? ['import { resolvePortalUser } from "./portal-auth.js";'] : []),
    "",
    "// Rate-limit the public, unauthenticated POST surface, keyed by client IP",
    "// (fixed-window KV counter that fails open). Derived from your config: the",
    "// editor magic-link always, plus the portal credential surfaces and checkout",
    "// when those are enabled. Add your own via `security.rateRules` in the config —",
    "// they're matched first, so they can also override a default's budget.",
    "// `env.RL` is read per request (a getter) — a KV binding is only valid in",
    "// request scope.",
    "const RATE_RULES = astroidRateRules(astroidConfig);",
    ...(portal
      ? [
          "const PORTAL_GUARD = astroidPortalGuardConfig(astroidConfig)!;",
          "",
          "// The PORTAL session — a second, cookie- and table-isolated Better Auth",
          "// instance beside the editor's. `resolvePortalSession` shares the in-flight",
          "// lookup per request, so the guard here and the handler that runs next",
          "// don't each pay a session round-trip.",
        ]
      : []),
    "",
    "export const onRequest = createLouiseMiddleware({",
    "  resolveEditor: (request) => resolveEditor(request),",
    "  rateLimit: { rules: RATE_RULES, kv: () => env.RL },",
    ...(portal
      ? [
          "  extend: async (context) => {",
          "    const user = await resolvePortalSession(context.request, resolvePortalUser);",
          "    context.locals.portalUser = user;",
          "  },",
          "  // Route guard: the declarative prefix→roles table from your config.",
          "  // An /api/* route always answers in JSON — redirecting fetch() to an",
          "  // HTML login page returns 200 and markup, which reads as success.",
          "  guard: (context) => {",
          "    const decision = portalGuard(",
          "      context.url.pathname,",
          "      context.locals.portalUser,",
          "      PORTAL_GUARD,",
          "    );",
          "    if (!decision) return undefined;",
          '    if (decision.kind === "redirect") return context.redirect(decision.location);',
          "    return guardResponse(decision) ?? undefined;",
          "  },",
        ]
      : []),
    "  // Rewrite Astro's hash-based style-src (owned by astroidSecurity in",
    '  // astro.config.mjs) to permit Louise\'s data-driven style="" + editor styles.',
    `  cspStyleSrc: ${JSON.stringify(cspStyleSrc)},`,
    "});",
    "",
  ].join("\n");
}
