// Copyright (c) 2026 BowenLabs. Astroid is MIT licensed.
//
// generateAstroidWorker / generateAstroidMiddleware — emit the Cloudflare Worker
// entrypoint and the Astro middleware a Louise site would otherwise hand-write.
// The worker's editor routes are composed in the fixed order from the route plan
// (routes.ts), so the "versionsRoute/searchRoute before pagesRoute" collision is
// impossible by construction. Pure string generation, like generateAstroidSchema.
//
// Two seams are marked with TODO(astroid) and filled by later slices: the auth
// `resolveEditor`, and the section-catalog `validate` on the pages routes.

import type { AstroidConfig } from "../config.js";
import { capturesInquiries } from "../schema/framework.js";
import { type AstroidEditorRouteName, astroidEditorRoutePlan } from "./routes.js";

// Astroid's default editable site_settings surface — the columns the Settings
// panel may write, and which of them hold a media-library image URL.
const DEFAULT_SETTINGS_COLUMNS = [
  "siteName",
  "tagline",
  "logoUrl",
  "faviconUrl",
  "brandColor",
  "secondaryColor",
  "tertiaryColor",
  "contactEmail",
  "contactPhone",
  "contactAddress",
  "socialLinks",
  "navLinks",
  "metaDescription",
  "defaultOgImageUrl",
  "disableIndexing",
];
const DEFAULT_SETTINGS_IMAGE_KEYS = ["logoUrl", "faviconUrl", "defaultOgImageUrl"];

/**
 * Generate the Worker entrypoint (`worker.ts`) from an Astroid config: the editor
 * routes in collision-free order, an R2 media-asset route, and the `composeWorker`
 * default export over Astro's SSR handler. Inquiry routes + the contact form are
 * emitted only when a brand captures inquiries.
 */
export function generateAstroidWorker(config: AstroidConfig): string {
  const inquiries = capturesInquiries(config);
  const mediaBase = config.deploy?.mediaBase ?? "/media";
  const seedName = config.theme.name;
  const plan = astroidEditorRoutePlan(config);

  const editorImports = [
    "DEFAULT_PAGE_FIELDS",
    ...new Set(plan.map((route) => route.factory)),
  ].sort();
  const tables = [
    "media",
    "pages",
    "pagesVersions",
    "siteSettings",
    ...(inquiries ? ["inquiries"] : []),
  ].sort();

  const routeCall = (name: AstroidEditorRouteName): string => {
    switch (name) {
      case "versions":
        return "versionsRoute({ table: pages, versionsTable: pagesVersions, config: pagesCollection, resolveEditor })";
      case "search":
        return "searchRoute({ table: pages, config: pagesCollection, resolveEditor })";
      case "pages":
        return 'pagesRoute({ table: pages, resolveEditor, fields: [...DEFAULT_PAGE_FIELDS, "sections"] })';
      case "save":
        return 'saveRoute({ resolveEditor, collections: { pages: { table: pages, fields: ["title", "seoTitle", "seoDescription"] } } })';
      case "settings":
        return "settingsRoute({ table: siteSettings, resolveEditor, columns: SETTINGS_COLUMNS, imageKeys: SETTINGS_IMAGE_KEYS, mediaBase: MEDIA_BASE })";
      case "media":
        return "mediaRoute({ table: media, resolveEditor })";
      case "editors":
        // Better Auth owns the `user` table (a NAME, not a Drizzle table), so this
        // route takes the default `"user"`; a `tablePrefix` would rename it.
        return 'editorsRoute({ table: "user", resolveEditor })';
      case "form":
        return "formRoute({ form: contactForm, rateLimitKv: (env) => env.RL })";
      case "inquiries":
        return "inquiriesRoute({ table: inquiries, resolveEditor })";
      case "seed":
        return `seedRoute({ table: siteSettings, resolveEditor, defaults: { siteName: ${JSON.stringify(seedName)} } })`;
    }
  };

  const lines: string[] = [];
  const p = (s = "") => lines.push(s);

  p("// Generated by astroidjs — do not hand-edit.");
  p("// Source: your defineAstroid config. The editor route ORDER is fixed by");
  p("// Astroid to avoid matcher collisions — see each route's note below.");
  p('import { handle } from "@astrojs/cloudflare/handler";');
  p("import {");
  for (const name of editorImports) p(`  ${name},`);
  p('} from "louise-toolkit/editor";');
  if (inquiries) p('import { defineForm } from "louise-toolkit/forms";');
  p('import { composeWorker, type WorkerRoute } from "louise-toolkit/worker";');
  if (inquiries) p('import { inquiriesForm } from "louise-toolkit/db";');
  p(`import { ${tables.join(", ")} } from "./schema.js";`);
  p('import { astroidPagesCollection } from "astroidjs";');
  p('import astroidConfig from "./astroid.config.js";');
  p("// TODO(astroid): your AUTH seam. resolveEditor resolves the editor session");
  p("// from a request; a truthy result authorizes editor writes. A generated auth");
  p("// module is a later slice.");
  p('import { resolveEditor } from "./auth.js";');
  p();
  p(`const MEDIA_BASE = ${JSON.stringify(mediaBase)};`);
  p("const pagesCollection = astroidPagesCollection(astroidConfig);");
  p();
  p("// Editable site_settings columns the Settings panel may write, and which of");
  p("// them resolve to a media-library asset.");
  p(`const SETTINGS_COLUMNS = ${JSON.stringify(DEFAULT_SETTINGS_COLUMNS)};`);
  p(`const SETTINGS_IMAGE_KEYS = ${JSON.stringify(DEFAULT_SETTINGS_IMAGE_KEYS)};`);
  if (inquiries) {
    p();
    p("// Public contact form: the built-in inquiries fields + silent spam");
    p("// heuristics (a honeypot + a minimum time-since-render).");
    p(
      'const contactForm = defineForm({ name: "inquiries", fields: inquiriesForm.fields, spam: { honeypot: "website", minSeconds: 2 } });',
    );
  }
  p();
  p("// TODO(astroid): sections validation (assertValidSections) is wired onto the");
  p("// pages/versions routes once the section catalog lands (a later slice).");
  p("const editorRoutes: WorkerRoute<CloudflareEnv>[] = [");
  for (const route of plan) {
    p(`  // ${route.note}`);
    p(`  ${routeCall(route.name)},`);
  }
  p("];");
  p();
  p("// Stream uploaded media back from R2 at MEDIA_BASE (self-hosted, no public bucket).");
  p("const mediaAssetRoute: WorkerRoute<CloudflareEnv> = async (request, env) => {");
  p("  const url = new URL(request.url);");
  p("  if (!url.pathname.startsWith(`${MEDIA_BASE}/`)) return undefined;");
  p("  const key = decodeURIComponent(url.pathname.slice(MEDIA_BASE.length + 1));");
  p("  if (!key) return undefined;");
  p("  const obj = await env.MEDIA.get(key);");
  p('  if (!obj) return new Response("Not found", { status: 404 });');
  p("  const headers = new Headers();");
  p("  obj.writeHttpMetadata(headers);");
  p('  headers.set("etag", obj.httpEtag);');
  p('  headers.set("cache-control", "public, max-age=31536000, immutable");');
  p('  headers.set("x-content-type-options", "nosniff");');
  p("  return new Response(obj.body, { headers });");
  p("};");
  p();
  p("export default composeWorker<CloudflareEnv>({");
  p("  routes: [...editorRoutes, mediaAssetRoute],");
  p("  fetch: (request, env, ctx) => handle(request, env, ctx),");
  p("});");
  p();

  return lines.join("\n");
}

/**
 * Generate the Astro middleware (`middleware.ts`) from an Astroid config: the
 * shared Louise flow (resolve editor session + sticky `?louise` edit mode →
 * content-freshness + security headers) via `createLouiseMiddleware`. Rate-limit
 * rules layer in once the config models them; auth is the same seam as the worker.
 */
export function generateAstroidMiddleware(_config: AstroidConfig): string {
  // Louise's brand font is bundled + base64-inlined (no Google Fonts host to
  // allow); createLouiseMiddleware auto-allows `data:` fonts in the CSP, so the
  // inlined @font-face needs no manual `font-src` entry.
  const cspStyleSrc = "'self' 'unsafe-inline'";
  return [
    "// Generated by astroidjs — do not hand-edit.",
    "// The shared Louise middleware: resolve the editor session + sticky ?louise",
    "// edit mode, then apply content-freshness + transport-security headers.",
    'import { createLouiseMiddleware } from "louise-toolkit/astro";',
    "// TODO(astroid): your AUTH seam — same resolveEditor as the generated worker.ts.",
    'import { resolveEditor } from "./auth.js";',
    "",
    "export const onRequest = createLouiseMiddleware({",
    "  resolveEditor: (request) => resolveEditor(request),",
    `  cspStyleSrc: ${JSON.stringify(cspStyleSrc)},`,
    "});",
    "",
  ].join("\n");
}
