// Copyright (c) 2026 BowenLabs. Astroid is MIT licensed.
//
// Real-visitor Core Web Vitals (#106 CWV) — the field-data half of the health
// co-pilot.
//
// `HealthSummary` has carried an optional `cwv` field since the health module
// landed, and the Health panel renders a "not measured yet" badge when it's
// absent. Astroid never populated it, so that badge was permanently accurate and
// permanently useless — the same dead-UI shape as the missing overview route.
//
// The loop has three parts and needs all three to close:
//
//   1. INGEST — a beacon in the page POSTs LCP/CLS/INP to `/api/louise/vitals`,
//      which writes a data point to an Analytics Engine dataset.
//   2. STORE — the `analytics_engine_datasets` binding. Free, and the route
//      degrades to accept-and-drop without it.
//   3. READ BACK — the daily health scan queries the p75 over the last day via
//      the Analytics Engine SQL API and folds it into the summary.
//
// Step 3 is the one with credentials: the SQL API is account-scoped and needs an
// API token, which no binding provides. So it follows the dormant-until-
// provisioned convention — collection runs regardless, and the badge stays "not
// measured yet" until the pair is real, rather than the scan erroring.

import type { AstroidConfig } from "../config.js";

/** The Analytics Engine dataset binding name. */
export const ASTROID_VITALS_BINDING = "VITALS";

/** The dataset name, derived from the project key so two Astroid sites on one
 *  account don't write into the same table. */
export function astroidVitalsDataset(config: AstroidConfig): string {
  return `${config.key.replace(/[^a-z0-9_]/gi, "_")}_web_vitals`;
}

/**
 * Credentials the CWV READ-BACK needs — not the collection.
 *
 * The Analytics Engine SQL API is account-scoped and has no binding, so a token
 * is unavoidable. Both are required together: an account id without a token (or
 * vice versa) can't query, so partial provisioning reads as dormant exactly like
 * every other Astroid module.
 */
export const ASTROID_VITALS_SECRET_NAMES = ["CF_ACCOUNT_ID", "CF_API_TOKEN"] as const;

/**
 * The public beacon, as a static `public/vitals.js`.
 *
 * A FILE rather than an inline script, and that is a CSP decision, not a style
 * one: Astro hashes the scripts it processes into `script-src`, and an
 * `is:inline` script carrying generated content cannot be hashed — it would be
 * blocked. Served from `public/`, it is same-origin and covered by
 * `script-src 'self'` with no policy change at all.
 */
export function generateAstroidVitalsBeacon(
  config: AstroidConfig,
  beacon: string,
): { path: string; contents: string } {
  void config;
  return {
    path: "public/vitals.js",
    contents: [
      "// Real-visitor Core Web Vitals beacon — generated by astroidjs.",
      "//",
      "// A static file, not an inline script: Astro hashes processed scripts into",
      "// script-src, and an is:inline script with generated content can't be",
      "// hashed, so it would be CSP-blocked. From public/ it is same-origin and",
      "// already covered by script-src 'self'.",
      "//",
      "// It reports once per page, on visibilitychange → hidden, via sendBeacon —",
      "// so it costs nothing on the critical path and never blocks unload.",
      beacon,
      "",
    ].join("\n"),
  };
}

/**
 * The health scan's CWV read-back, as source for the generated worker.
 *
 * Returns `undefined` — so the badge stays "not measured yet" — when the API
 * credentials aren't set, the query fails, or there is no field data yet. Never
 * throws: a failed vitals query must not take down the rest of the health scan,
 * which is mostly cheap COUNTs that have nothing to do with it.
 */
export function generateAstroidCwvQuery(config: AstroidConfig): string[] {
  const dataset = astroidVitalsDataset(config);
  return [
    "// Real-visitor CWV over the last day, from the Analytics Engine SQL API.",
    "//",
    "// The SQL API is account-scoped and has no binding, so it needs a token.",
    "// Unprovisioned (or a failed query, or no field data yet) → undefined, and",
    "// the Health panel shows 'not measured yet' rather than the scan failing.",
    "async function queryCwv(env: CloudflareEnv) {",
    "  const accountId = await readModuleSecret(env.CF_ACCOUNT_ID);",
    "  const token = await readModuleSecret(env.CF_API_TOKEN);",
    "  if (!accountId || !token) return undefined;",
    "  try {",
    "    const res = await fetch(",
    "      `https://api.cloudflare.com/client/v4/accounts/${accountId}/analytics_engine/sql`,",
    "      {",
    '        method: "POST",',
    "        headers: { authorization: `Bearer ${token}` },",
    `        body: cwvSqlQuery(${JSON.stringify(dataset)}, 24),`,
    "      },",
    "    );",
    "    if (!res.ok) return undefined;",
    "    const body = (await res.json()) as {",
    "      data?: { metric?: unknown; p75?: unknown; samples?: unknown }[];",
    "    };",
    "    const summary = summarizeCwv(parseCwvRows(body.data ?? []));",
    "    return summary.sampleSize > 0 ? summary : undefined;",
    "  } catch {",
    "    return undefined;",
    "  }",
    "}",
  ];
}
