// Copyright (c) 2026 BowenLabs. Astroid is MIT licensed.
//
// generateAstroidSchema — emit the Drizzle schema source (a site's `schema.ts`)
// from an Astroid config. This is the boilerplate every Louise site hand-writes:
// compose the framework `pagesColumns` into a `pages` table, add the versions
// table + publish pointer, and re-export the ready-made framework tables. Astroid
// generates it, driven by the single-brand config.
//
// Pure string generation, mirroring louise-toolkit/content's own
// `generateSchemaSource`: the caller (the Astroid CLI, a later slice) writes the
// result to disk and formats it. Import ordering matches the site's schema.ts so
// a formatter never re-flags the generated file.

import { generateCatalogTable } from "../commerce/mirror.js";
import type { AstroidConfig } from "../config.js";
import { astroidFrameworkTables } from "./framework.js";

/**
 * Generate the TypeScript source of a site's Drizzle schema from an Astroid
 * config. The output is a drop-in replacement for the hand-written `schema.ts`:
 * a `pages` table composed from `pagesColumns`, a `pages_versions` snapshot
 * table, and the re-exported framework tables the config selects.
 */
export function generateAstroidSchema(config: AstroidConfig): string {
  const framework = astroidFrameworkTables(config); // sorted
  // pagesColumns is spread into `pages`; the framework tables are re-exported.
  // One import brings them all in (matching the site) so nothing is unused.
  const dbImports = [...framework, "pagesColumns"].sort();
  const catalog = generateCatalogTable(config);
  // Only import the column builders the emitted source actually uses — an
  // unused import is a lint error in the project we're generating into, and a
  // missing one (`real`, from the catalog's price/sortOrder) is a type error.
  const drizzleImports = ["integer", "sqliteTable", "text"];
  if (catalog?.includes("real(")) drizzleImports.push("real");

  return [
    "// Generated by astroidjs — do not hand-edit.",
    "// Source: your defineAstroid config.",
    `import { ${drizzleImports.sort().join(", ")} } from "drizzle-orm/sqlite-core";`,
    'import { collectionVersionsTable, type JsonValue } from "louise-toolkit/content";',
    `import { ${dbImports.join(", ")} } from "louise-toolkit/db";`,
    "",
    'export const pages = sqliteTable("pages", {',
    "  ...pagesColumns,",
    "  // Structured page-builder blocks (the editable home), rendered by the",
    "  // site's own section components.",
    '  sections: text("sections", { mode: "json" }).$type<JsonValue>(),',
    "  // Nullable pointer to the live version (pages_versions.id); NULL = unpublished.",
    '  publishedVersionId: integer("published_version_id"),',
    "});",
    "",
    "// Version snapshots for pages. Field-independent — each saved version is one",
    "// JSON blob — so the table only needs the slug.",
    'export const pagesVersions = collectionVersionsTable({ slug: "pages", fields: {} });',
    "",
    ...(catalog ? [catalog] : []),
    `export { ${framework.join(", ")} };`,
    "",
    "// Site-owned tables (the ones Astroid doesn't manage): a project declares",
    "// its own Drizzle tables in src/schema.site.ts and they're re-exported here",
    "// so drizzle-kit sees them and the generated worker can import them. The file",
    "// is scaffold-once — empty until a project adds a table — so this re-export is",
    "// always safe.",
    'export * from "./schema.site.js";',
    "",
  ].join("\n");
}
