import { defineConfig } from "drizzle-kit";

// Generates D1 (SQLite) migrations from src/schema.ts into ./migrations, applied
// by `wrangler d1 migrations apply DB`. The schema is the astroid-generated
// content tables (louise-toolkit/db column sets).
//
// Better Auth owns its own tables (user/session/account/verification/passkey) —
// they're generated by `louise gen-auth-schema` (see migrations/0001_auth.sql),
// NOT by Drizzle, so they're fenced out here to keep drizzle-kit from trying to
// drop or recreate them.
export default defineConfig({
  dialect: "sqlite",
  schema: "./src/schema.ts",
  out: "./migrations",
  tablesFilter: ["!user", "!session", "!account", "!verification", "!passkey"],
});
